### ISSUE TITLE
Should this work also with other Nordnet country sites?

### ISSUE THREAD

**Issue by ristomatti** [jippi/hass-nordnet#5]
While skimming through the source, I noticed each endpoint is hardcoded to a .nordnet.dk domain. Do you know if anyone has tried using this with nordnet.se/no/fi?

Naturally I'm a "bit" skeptical if this would be a very good idea given the unfortunate API key limitations. I remember spotting an announcement for an upcoming API interface several years ago. After nothing appeared within the next 6 months I contacted the customer service to ask for updates, only to find the development has halted and that they can not give any estimate when it will become available.

Nice to see the functionality has at least appeared but no ability to create a read-only API key is definitely not great.

**Comment by jippi** [comment]
Hey,

I'm able to login on nordnet.dk/no/fi/se with my Danish credentials, so i would imagine it would work via the API as well - if not, I'll make a country selector available to fix it :) 

I'm also incredible disappointed that they do not provide any API token system, considering that they have the full API, well documented and functional - they use it for both their web and mobile apps.

I'm incredible upset that I have to ask people to put in their regular username+password into Home Assistant and my plugin, it's a huge leap of faith that I'm not doing something bad or leaking credentials :(

**Comment by ristomatti** [comment]
I'm a bit surprised the login is not tied to a specific country, thanks! I might give this a try at some point. Out of curiosity if not else.

> I'm incredible upset that I have to ask people to put in their regular username+password into Home Assistant and my plugin, it's a huge leap of faith that I'm not doing something bad or leaking credentials :(

I would feel the same way but what can you do. At least HACS will download the code direct from the repo, right? Then anyone can come and check the code like I did. I don't even code in Python, but I figured I might pick up if there's something obviously suspicious going on :slightly_smiling_face:

**Comment by jippi** [comment]
> At least HACS will download the code direct from the repo, right? 

Yep, no way for me to do anything bad in secret when on the official HACS store :) 

It's my first real python project in many many many years, so hopefully it was somewhat readable and ~easy to follow :) I do try my best to document and name things in a sane way

**Comment by ristomatti** [comment]
The code looked very clean and easy to follow to my primarily JS/TS/Java programmer eyes. :+1:

I've occasionally needed to debug/hack some Python code which has refused to run. Many of them have looked quite incomprehensible, some so daunting I didn't even try. :slightly_smiling_face:
